baseurl: /

repository: Gothor/asobou-website

timezone: Europe/Paris

links:
  youtube:   https://www.youtube.com/channel/UCInlRcOYH0chCOKcvTlFfog
  twitch:    https://www.twitch.tv/asoboujeuxjapon
  instagram: https://www.instagram.com/asoboujeuxjapon/
  facebook:  https://www.facebook.com/Asobou-Jeux-et-Japon-652178235230171/
  twitter:   https://twitter.com/AsobouJeuxJapon

collections:
  Japon: { output: true }
  Jeux:  { output: true }

defaults:
  - scope: { path: "", type: "Japon" }
    values:
      layout: "video"
  - scope: { path: "", type: "Jeux" }
    values:
      layout: "video"