baseurl: /

repository: Gothor/asoubou-website

timezone: Europe/Paris

links:
  youtube:   https://www.youtube.com/channel/UCInlRcOYH0chCOKcvTlFfog
  twitch:    https://www.twitch.tv/asoubou
  instagram: https://www.instagram.com/asoubou_insta/
  facebook:  https://www.facebook.com/asoubou.jeux.et.japon/
  twitter:   https://twitter.com/asoubou

collections:
  Japon: { output: true }
  Jeux:  { output: true }

defaults:
  - scope: { path: "", type: "Japon" }
    values:
      layout: "video"
  - scope: { path: "", type: "Jeux" }
    values:
      layout: "video"